### ISSUE TITLE
Please move "use strict" inside the IIFE

### ISSUE THREAD

**Issue by Andrew-Cottrell** [adityakahb/amegmen#3]
https://github.com/adityakahb/amegmen/blob/48ad5ac077466550e2067937a553835e3e7f1616/dist/scripts/amegmen.js#L1

A top level `"use strict"` declaration may cause issues for other scripts concatenated in the same file.

A safer approach is
```javascript
(function (AMegMen) {
    "use strict";
    var AllAMegMenInstances = {};
```

**Comment by adityakahb** [comment]
Strict mode is now a part of AMegMen function.
