### ISSUE TITLE
Use of legacy `event` object causes "SCRIPT438" error in some browsers

### ISSUE THREAD

**Issue by Andrew-Cottrell** [adityakahb/amegmen#5]
Various event handler functions are accessing the legacy `event` object rather than using an `event` handler parameter.

- https://github.com/adityakahb/amegmen/blob/v1.0.3/src/ts/amegmen.ts#L569
- https://github.com/adityakahb/amegmen/blob/v1.0.3/src/ts/amegmen.ts#L639
- https://github.com/adityakahb/amegmen/blob/v1.0.3/src/ts/amegmen.ts#L704
- https://github.com/adityakahb/amegmen/blob/v1.0.3/src/ts/amegmen.ts#L721
- https://github.com/adityakahb/amegmen/blob/v1.0.3/src/ts/amegmen.ts#L740

In some browsers the legacy `error` object is different to the `event` handler parameter. 

Specifically, in IE 9, the legacy `error` object is an instance of `MSEventObj` that does _not_ support the `preventDefault` method. This leads to the following console error
>**SCRIPT438:** Object doesn't support property or method 'preventDefault'

Reference: https://all-markup-news.com/dom-level-3-events-support-in-ie9/
>Registration using the HTML event attributes (and their properties) will simultaneously enable the MSEventObj (legacy event object) through the `window.event` property as well as the new DOM event via the event handler parameter. We do this because the HTML event attribute registration technique is ambiguous—e.g., did the web developer expect the new DOM Events model or the old IE one?

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Window/event
>You _should_ avoid using this property in new code, and should instead use the `Event` passed into the event handler function. This property is not universally supported and even when supported introduces potential fragility to your code.
>**Note:** This property can be fragile, in that there may be situations in which the returned `Event` is not the expected value.

Reference: https://dom.spec.whatwg.org/#dom-window-event
>Web developers are strongly encouraged to instead rely on the `Event` object passed to event listeners, as that will result in more portable code.

Suggested fix is to _always_ use an `event` handler parameter and _never_ use the legacy `event` object.

**Comment by adityakahb** [comment]
Updated EventHandlers with v1.0.5 release to include `event` parameter.
